### ISSUE TITLE
Django 1.7 System Check throws "(1_6.W001) Some project unittests may not execute as expected"

### ISSUE THREAD

**Issue by shearichard** [SwingTix/bookkeeper#7]
The system checker in 1.7 hightlights the fact that test discovery has altered in 1.7.

The message goes away if you add the following to settings:
```
TEST_RUNNER = 'django.test.runner.DiscoverRunner'
```

It seems to me that tests are running OK in 1.7 (which is what the warning message is asking you to check) so I'm going to do the above.

**Comment by g--** [comment]
Fixed!  Thanks!
